### PR TITLE
Technology button

### PR DESCRIPTION
**Pull request by martinhartt**
### Motivation

To improve page views for the technology report by changing link to button and adding link to image.

### Pre-merge checklist

- [ ] Documentation
- [ ] Unit tests
- [ ] Reviews
  - [ ] Code review
  - [ ] Design review
- [ ] Manual testing
  - [ ] Windows 7 IE 11
  - [ ] Windows 10 Edge
  - [ ] Mac OS El Capitan Safari
  - [ ] Mac OS El Capitan Chrome
  - [ ] Mac OS El Capitan Firefox
  - [ ] iOS 9 Safari
  - [ ] Android 6 Chrome
  - [ ] Listen to the site on a screen reader
  - [ ] Navigate the site using the keyboard only
- [ ] Tester approved

### CODE REVIEW

**Comment by chris-brookes** [comment]
@martinhartt - Please can you change the style of the button to a ._links_primaryButton
(font 24px, more padding etc.)

**Comment by chris-brookes** [comment]
@martinhartt - Do we need the arrow in the css any more?

**Comment by martinhartt** [comment]
@chris-brookes Nope, just removed them

**Comment by matt-paul** [comment]
Looks good to me!

**Comment by gregdorward** [comment]
Fixes #{{566}}

**Pull request merged**
