### PR TITLE
Ux testing jobs link in header

### PR DESCRIPTION
**Pull request by callerc1**
### Motivation

-  As a user I want to be able to find the Join Us Section efficiently so I can View RB vacancies.

### Test plan

- TODO: Write a test plan.

### Pre-merge checklist

- [ ] Documentation
- [ ] Unit tests
- [ ] Reviews
  - [ ] Code review
  - [ ] Design review
- [ ] Manual testing
  - [ ] Windows 7 IE 11
  - [ ] Windows 10 Edge
  - [ ] Mac OS El Capitan Safari
  - [ ] Mac OS El Capitan Chrome
  - [ ] Mac OS El Capitan Firefox
  - [ ] iOS 9 Safari
  - [ ] Android 6 Chrome
  - [ ] Listen to the site on a screen reader
  - [ ] Navigate the site using the keyboard only
- [ ] Tester approved

### CODE REVIEW

**Comment by chris-brookes** [comment]
@callerc1 - The tracking doesn't seem to be working. Looks like you are missing the span tags.

**Comment by callerc1** [comment]
@chris-brookes Ready for re test.

**Comment by chris-brookes** [comment]
In IE11, when viewed on the smallest tablet size (690px width), the 'Jobs' link gets cut off out of view.

screen shot 2017-08-02 at 17 47 59

**Comment by gregdorward** [comment]
Fixes #{{issue number}}

**Pull request merged**
