### PR TITLE
load fonts from typography.com asynchronously

### PR DESCRIPTION
**Pull request by dstodolny**
### Motivation

- [Related story 1](https://github.com/redbadger/website-honestly/issues/438)
- [Related story 2](https://github.com/redbadger/website-honestly/issues/434)

### Test plan

```
git clone https://github.com/dstodolny/typography-com-test
cd typography-com-test
npm i
node typography.js
```
In index.ejs of website-honestly, replace the url in the stylesheet link from https://cloud.typography.com... to http://localhost:3000/ (the node express server)

```
<link rel="preload" href="http://localhost:3000/" as="style" onload="this.rel='stylesheet'" />
<noscript><link rel="stylesheet" href="http://localhost:3000/"></noscript>
```
 
See if it loads fallback fonts first and then after 5 seconds loads correct fonts.

### Pre-merge checklist

- [ ] Documentation
- [ ] Unit tests
- [ ] Reviews
  - [ ] Code review
  - [ ] Design review
- [ ] Manual testing
  - [ ] Windows 7 IE 11
  - [ ] Windows 10 Edge
  - [ ] Mac OS El Capitan Safari
  - [ ] Mac OS El Capitan Chrome
  - [ ] Mac OS El Capitan Firefox
  - [ ] iOS 9 Safari
  - [ ] Android 6 Chrome
  - [ ] Listen to the site on a screen reader
  - [ ] Navigate the site using the keyboard only
- [ ] Tester approved

### CODE REVIEW

**Comment by lpil** [comment]
This'll result in the fonts popping in after the user has started reading the content, which is quite jarring. Worth doing user testing with?

**Comment by gregdorward** [comment]
Yeah, @lpil it's something that I intend to get the UX team across. I'm expecting performance gains, but we want to make sure those benefits outweigh the potential UX consequences.

@dpiatek if we decide that the experience is too jarring, is it possible to pull the fonts from the two different sources (removing the dependencies), without the asynchronous loading?

**Comment by lpil** [comment]
The Guardian caches their fonts in localstorage and only makes the request if it's not there. That could be another option.

**Comment by gregdorward** [comment]
looping @grahammendick into the discussion, as he did a fair bit of investigation into how we use Typography, and can probably answer your question @lpil (providing he has the time to)

**Comment by grahammendick** [comment]
It’s FOIT (flash of invisible text - current behaviour) vs FOUT (flash of unstyled text - proposed new behaviour), right? If Typography takes a long time to respond then the flash of invisible text can be much longer than just a flash and can even cause an outage, #434. (Caching in local storage won’t solve the the slowness/outage on first visit.)

**Comment by gregdorward** [comment]
@romanschejbal when you've got a chance, I think this one still needs a review. We've tested most of it, but we ultimately need to leave it to the UXD team to make a call on whether we push it to production

**Pull request merged**
