### PR TITLE
Changing placeholder email

### PR DESCRIPTION
**Pull request by mveritym**
### Motivation

Stop confusing men named Sam.

### Test plan

Check it says `name@example.com`

### Pre-merge checklist

- [ ] Reviews
  - [ ] Code review
  - [ ] Design review
- [ ] Manual testing
  - [ ] Windows 7 IE 11
  - [ ] Windows 10 Edge
  - [ ] Mac OS El Capitan Safari
  - [ ] Mac OS El Capitan Chrome
  - [ ] Mac OS El Capitan Firefox
  - [ ] iOS 9 Safari
  - [ ] Android 6 Chrome
  - [ ] Listen to the site on a screen reader
  - [ ] Navigate the site using the keyboard only
- [ ] Tester approved

### CODE REVIEW

**Comment by dstodolny** [comment]
aiszow3

**Comment by chris-brookes** [comment]
@mveritym - I see you must have checked to make sure you can use that website email address "You may use this domain in examples without prior coordination or asking for permission." :-)
www.example.com

**Comment by chris-brookes** [comment]
@Roisi @mveritym  - Should we not make all the example emails the same?

screen shot 2017-03-21 at 15 17 26

**Comment by Roisi** [comment]
if possible yes, its a bit random at the moment and if we've hit on something appropriate we should use everywhere

**Pull request merged**
