### PR TITLE
apply design improvemnt to the case study retailer page

### PR DESCRIPTION
**Pull request by dstodolny**
### Motivation

- made "Project in mind?" box to be fluid
- added more space below tech image

### Pre-merge checklist

- [ ] Documentation
- [ ] Unit tests
- [ ] Reviews
  - [ ] Code review
  - [ ] Design review
- [ ] Manual testing
  - [ ] Windows 7 IE 11
  - [ ] Windows 10 Edge
  - [ ] Mac OS El Capitan Safari
  - [ ] Mac OS El Capitan Chrome
  - [ ] Mac OS El Capitan Firefox
  - [ ] iOS 9 Safari
  - [ ] Android 6 Chrome
  - [ ] Listen to the site on a screen reader
  - [ ] Navigate the site using the keyboard only
- [ ] Tester approved

### CODE REVIEW

**Comment by gregdorward** [comment]
If possible, I think we need to maintain a width of 100% for the contactBox on mobile viewports, as 27% of the screen space is not enough in this case. This looks to be the case for any screen width below 736px

screen shot 2017-03-30 at 14 19 37

**Comment by chris-brookes** [comment]
@dstodolny - The padding on the bullet points need to be changed to a % when in desktop view.

screen shot 2017-03-30 at 14 55 40

**Comment by chris-brookes** [comment]
@dstodolny - should you not change the right padding on the bullet points to a % too? Like all of the other right padding values.

**Comment by dstodolny** [comment]
3kpq4m

**Pull request merged**
