### PR TITLE
Changed link colour to badgerBlack

### LINKED ISSUE #249: Link text same colour as background
there is either missing text or text the same colour as the background on the 404 page
screen shot 2016-12-13 at 12 06 21

### PR DESCRIPTION
**Pull request by grahammendick**
### Motivation

Fixes #249 

### Test plan

Enter an invalid path, e.g., https://www-staging.red-badger.com/xxx, and check the links show up

### Pre-merge checklist

- [ ] Documentation
- [ ] Unit tests
- [ ] Reviews
  - [ ] Code review
  - [ ] Design review
- [ ] Manual testing
  - [ ] Windows 7 IE 11
  - [ ] Windows 10 Edge
  - [ ] Mac OS El Capitan Safari
  - [ ] Mac OS El Capitan Chrome
  - [ ] Mac OS El Capitan Firefox
  - [ ] iOS 9 Safari
  - [ ] Android 6 Chrome
  - [ ] Listen to the site on a screen reader
  - [ ] Navigate the site using the keyboard only
- [ ] Tester approved

### CODE REVIEW

**Comment by asavin** [comment]
Doesn't seems to be working on a preview app: https://www-staging.red-badger.com/6d57ac4/bla

**Comment by grahammendick** [comment]
I've made some progress. My styling change did make it onto the branch. You can see this by going directly to the 404 page, https://www-staging.red-badger.com/6d57ac4/404/

But, it seems that if you hit and invalid URL then this 404 page isn't served! Don't know where's it getting the 404 page from!?

**Comment by asavin** [comment]
Ah right that was the proxy picking up an invalid route and redirecting to a default 404

**Comment by grahammendick** [comment]
This is now ready for review. It can't be tested on the Deployment version. It needs to be tested on Staging.
This goes along with the website-next-proxy PR, https://github.com/redbadger/website-next-proxy/pull/21. They should both be merged at the same time.

**Pull request merged**
