### PR TITLE
Add hubspot buttons

### PR DESCRIPTION
**Pull request by dpiatek**
#### Trello Ticket / Github Issue Link

https://trello.com/c/c6Lvvmfm/120-hubspot-track-our-ctas-with-hubspot

#### Description

Add hubspot call to action snippets. They should look like the old buttons, though they are images so might differ a little bit. The buttons still lead to the same places, but redirect through hubspot.

https://knowledge.hubspot.com/cta-user-guide-v2
https://app.hubspot.com/ctas-beta/4210858 (needs login) 

#### Areas of risk, including severity per area (low :blush:, medium :grimacing:, high :scream:)

😊 Tech page

#### Test plan

The buttons do not track anything if they are not under the correct domain, so this should be tested on staging (though this is an assumption; the buttons work locally but the analytics are not registering in hubspot).

#### Does this affect any marketing tests (ie. hubspot scripts)?

Yes, the buttons send click analytics to hubspot.

### CODE REVIEW

**Comment by matt-paul** [comment]
**In test....**
- Webinar button not using hubspot

**Comment by matt-paul** [comment]
**In test**
Webinar button - right padding disappears between 980px and 1040px 
@dpiatek ^

**Comment by dpiatek** [comment]
@matt-paul done!

**Comment by JunBadger** [comment]
meetup-hover
meetup
read pdf hover 2x
read pdf 2x
slack-hover
slack
watch - hover 2x
watch 2x

**Pull request merged**
