### PR TITLE
Financial Times case study

### PR DESCRIPTION
**Pull request by martinhartt**
### Motivation

- [Financial Times Case Study](https://trello.com/c/Xw8umwCs/30-ft-case-study-port)

### Test plan

- TODO: Write a test plan.

### Pre-merge checklist

- [ ] Documentation
- [ ] Unit tests
- [ ] Reviews
  - [ ] Code review
  - [ ] Design review
- [ ] Manual testing
  - [ ] Windows 7 IE 11
  - [ ] Windows 10 Edge
  - [ ] Mac OS El Capitan Safari
  - [ ] Mac OS El Capitan Chrome
  - [ ] Mac OS El Capitan Firefox
  - [ ] iOS 9 Safari
  - [ ] Android 6 Chrome
  - [ ] Listen to the site on a screen reader
  - [ ] Navigate the site using the keyboard only
- [ ] Tester approved

**NOTE**: This page is purposely missing the the quote and table components at the top of the page, as they are being developed in the Camden Market case study PR. Once that PR has merged, the page will be updated*

### CODE REVIEW

**Comment by chris-brookes** [comment]
@martinhartt - (Desktop) The image should be spread across the whole height of the header section, so it looks like the title is cutting into the image. You should change the max-height to 456px. 

screen shot 2017-07-13 at 14 33 15

**Comment by martinhartt** [comment]
Thanks for your comment @chris-brookes. In the [zeplin.io](https://app.zeplin.io/project/57c8297fc3cf63795b6a4520/screen/5963615dee0d8e7a5c2ab9a6) designs, the image appears to be on top of the section, not behind it:

screen shot 2017-07-13 at 15 08 46

I showed it to Monika and she seemed to approve of it like this. I'll ask again for confirmation though.

**Comment by chris-brookes** [comment]
@martinhartt - A few margin changes
- The H3 titles should have 0px bottom margin. (including the ones above the lists. This is different to the design page. This is also ok if it affects the retail case study page.)
- 40px between each section.
- 20px between each paragraph in each section.

screen shot 2017-07-27 at 13 15 10


I have confirmed these changes with Monika.

**Comment by chris-brookes** [comment]
@martinhartt - Above H3 titles should be a 40px margin.

**Comment by chris-brookes** [comment]
@martinhartt - The font size in the Results table should be 16px in all views (The title is right. 20px)

**Comment by chris-brookes** [comment]
Mobile view - Text in the results table should be 16px

**Comment by chris-brookes** [comment]
Got the designer sign-off.... all ready to go.

**Pull request merged**
