### PR TITLE
Webinar modal

### PR DESCRIPTION
**Pull request by pataruco**
### Motivation
On the events page, we had a call to action (CTA) banner for registering users on webinars, we are using a third party Saas to handle this registration, so we want to make this within our site without going to another site.

This implementation is a quick fix. Developer team suggested to marketing that we can create a custom form using Webinar Saas API.

### Test plan

Please, go to the [events page](https://www-staging.red-badger.com/05b9bd3/about-us/events/), then click on the banner and a modal will pop-up with a webinar registration form. Please fill the form and you will receive an email

### Pre-merge checklist

- [ ] Documentation
- [ ] Unit tests
- [ ] Reviews
  - [ ] Code review
  - [ ] Design review
- [ ] Manual testing
  - [x] Windows 7 IE 11
  - [x] Windows 10 Edge
  - [x] Mac OS El Capitan Safari
  - [x] Mac OS El Capitan Chrome
  - [x] Mac OS El Capitan Firefox
  - [x] iOS 9 Safari
  - [x] Android 6 Chrome
  - [ ] Listen to the site on a screen reader
  - [ ] Navigate the site using the keyboard only
- [ ] Tester approved

### CODE REVIEW

**Comment by robbiemccorkell** [comment]
@pataruco Looks decent. One kinda UX suggestion I have is to try and lock the body scroll while the modal is open. Which admittedly is quite tricky and always hacky.

On one of my previous projects I did this by setting `overflow: hidden` on the `body` tag while the modal is open. But this is obviously quite dodgy because the modal component would need to reach out and affect an element above it.

I made it less dodgy on that project by having the open/close of the modal handled by redux, and a separate component at the top of the tree called `<BodyScroll />` that listens to the same prop and messes with the body scrolling. But obviously that was a very different architecture.

What do you think?

**Comment by pataruco** [comment]
Hi @robbiemccorkell, Thanks for your suggestions. I added `overflow: hidden` on the body tag when modal is open

**Comment by robbiemccorkell** [comment]
Cool, looks good. Do you need me to do any of the browser testing in the checklist?

**Comment by pataruco** [comment]
@declanslevin is working on the tests, thanks @robbiemccorkell

**Comment by declanslevin** [comment]
There are some issues on mobile devices - the text and image are not playing nice with each other, the widget reduces the available screen space so that the text gets compressed on Android, while on iOS it displays a single word:
Android 7 - Samsung Galaxy S8+ - Chrome
bs_realdroid_mobile_samsung galaxy s8 plus-7 0-1440x2960
iOS 11 - iPhone 8+ - Safari
bs_realios_mobile_iphone 8 plus-11 0

**Comment by declanslevin** [comment]
Another (more serious) issue on iOS 11 Safari is that you can't scroll within the widget, it scrolls the main page instead. This prevents you from scrolling down to the "Register" button.

**Comment by pataruco** [comment]
Hi @declanslevin I change the width on mobile to have more space for those items and I enabled scroll on iOS, please can you take a look [https://www-staging.red-badger.com/bf622b6/](https://www-staging.red-badger.com/bf622b6/)

**Comment by declanslevin** [comment]
I started testing the new changes and found some issues (will add them as individual comments to avoid confusion)

On Android, the height of the widget is condensed to the top of the screen space:
bs_realdroid_mobile_samsung galaxy s8 plus-7 0-1440x2960 1

This also affects desktop chrome/firefox/safari when the screen width is reduced:
screen shot 2017-12-04 at 10 15 20 2

**Comment by declanslevin** [comment]
The 'Close' button is missing from the widget so now it can't be closed once opened - this affects iOS Safari and Android Chrome (and also desktop browsers when the width is reduced, like in the previous comment)
screenshot at dec 04 10-54-11

**Comment by declanslevin** [comment]
Also, the main page still scrolls in the background on iOS Safari - can't see if this also affects Android as the main page is not visible in its current iteration.

**Comment by pataruco** [comment]
Hi @declanslevin, made the amends you suggested. Please take a look [here](https://www-staging.red-badger.com/eba8ced/about-us/events)

**Comment by declanslevin** [comment]
The original issue with iOS (tested iPhone 6S+ [9.0] and iPhone 8+ [11.0])  is back - scroll isn't working so it is stuck like follows:
bs_realios_mobile_iphone 8 plus-11 0 1

**Comment by pataruco** [comment]
Hi @declanslevin, please try this [one](https://www-staging.red-badger.com/58ad692/about-us/events)

**Pull request merged**
