### PR TITLE
Adding Bugsnag integration

### PR DESCRIPTION
**Pull request by asavin**
### Motivation

- Improving monitoring of the publish lambda

### Test plan

- Publish the site. Check Bugsnag.com for the data.

### Pre-merge checklist

- [ ] Documentation
- [ ] Unit tests
- [ ] Reviews
  - [ ] Code review
  - [ ] Design review
- [ ] Manual testing
  - [ ] Windows 7 IE 11
  - [ ] Windows 10 Edge
  - [ ] Mac OS El Capitan Safari
  - [ ] Mac OS El Capitan Chrome
  - [ ] Mac OS El Capitan Firefox
  - [ ] iOS 9 Safari
  - [ ] Android 6 Chrome
  - [ ] Listen to the site on a screen reader
  - [ ] Navigate the site using the keyboard only
- [ ] Tester approved

### CODE REVIEW

**Comment by JoeStanton** [comment]
Right - we're doing nothing wrong here. Bugsnag seem to return a `200 OK` for our exceptions, but then don't actually accept the error. They say in the docs it means the exception has been "queued for processing", which means it might not even be valid.

Not entirely sure why an error created with `bugsnag.notify(new Error("blah"))` would be invalid, have asked support. Blocked until a response.

**Comment by asavin** [comment]
That's a bit bold on their side to always respond with 200 :-O

**Comment by JoeStanton** [comment]
A 202 would certainly be more appropriate!

**Comment by asavin** [comment]
Closing this one for now, we can revisit it later

**Pull request closed without merging**
